version: "3"
networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    build: ./db
    volumes:
      - ./db/mongodb:/var/lib/mongodb
    ports:
      - "33335:27017"
    networks:
      - app-tier

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./api:/bin/api
    ports:
      - "8080:8080"
    links:
      - mongodb
    networks:
      - app-tier

  frontend:
    stdin_open: true
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/src:/var/lib/frontend
    ports:
      - "3000:3000"
